### ISSUE TITLE
Not an issue, but a question about AddPackageAsync

### ISSUE THREAD

**Issue by Noemata** [colinkiama/UWP-Package-Installer#16]
I'm running into an odd issue with AddPackageAsync.  Sometimes it hangs.  When it does hang, the package is installed anyway.  This happens rather frequently.  I'm really at a loss as to what the issue might be.

I was inspired by some of your code.  You can find my repo here: https://github.com/Noemata/AppxInstaller

The hang occurs in AppxBundle.cs on line 247.  I think the problem is on my end, but I'm starting to wonder since the code works as often as it does not.

```
                // MP! fixme: why do we hang on the await on occasion?
                Debug.WriteLine("Installing package ...");
                DeploymentResult result = await pkgManager.AddPackageAsync(uriToAppx, urisToDependencies, DeploymentOptions.ForceTargetApplicationShutdown).AsTask(progressCallback).WaitOrCancel(stop);
                Debug.WriteLine("Package installed ...");
```

**Comment by colinkiama** [comment]
If I remember correctly, we concluded that the issue was with .Net 5. Is it okay if I close this issue?

**Comment by Noemata** [comment]
Yes, close the issue.  Sorry for posting this here, just that I wasn't getting anywhere with this.
