### ISSUE TITLE
LTSC

### ISSUE THREAD

**Issue by timea-techgirl** [colinkiama/UWP-Package-Installer#18]
I installed this on LTSC through PowerShell but installed apps don't run, gives an error.
There’s a problem with "App Name". Contact your system administrator about repairing or reinstalling it.

**Comment by colinkiama** [comment]
I haven't tested this app on the LTSC branch so I'm going to have to play detective 😅.

So could you tell me the steps you took when attempting to install this app with Powershell? (Please include file names)

**Comment by timea-techgirl** [comment]
Just by installing the dependencies for my architecture `x64` with the `Add-AppxPackage -Path` command and finally the main package. It works great, I like it.

The problem I have is related to paid apps. I was testing an app I bought on emulator with LTSC.
Free apps don't have this problem. Some paid apps work fine, that's the mystery I couldn't find an answer to.

There are many conflict errors while installing dependencies for apps but didn't come across these errors with the native app installer. UWP is so messy.

I have some suggestions.
- Support for msix, eappxbundle and whatever other formats that microsoft has cooked up.
- The installation window can be made smaller like the native app installer, it looks neater.

Thanks a lot!
