### ISSUE TITLE
Cannot install. Certificat ran out

### ISSUE THREAD

**Issue by NightHammer1000** [colinkiama/UWP-Package-Installer#5]
As in title.

**Comment by colinkiama** [comment]
Currently unable to release a new package/certificate. If anyone else can generate a package/certificate, please reply to this thread.

Otherwise, it's going to be several weeks before I can fix this issue myself. Sorry.

**Comment by colinkiama** [comment]
There's a new release with an update certificate now!: https://github.com/colinkiama/UWP-Package-Installer/releases/tag/1.9.5.0
