### ISSUE TITLE
certificates expired, please update

### ISSUE THREAD

**Issue by Superhackman** [colinkiama/UWP-Package-Installer#6]
![image](https://user-images.githubusercontent.com/27593140/66188218-59341800-e64c-11e9-80d7-8985f4957737.png)

**Comment by colinkiama** [comment]
Need a bit of time. Comment again if this isn't resolved in the next 7 days

**Comment by colinkiama** [comment]
Working on it...

**Comment by colinkiama** [comment]
Made a certificate that lasts 10 years. That should be enough time before use of this app isn't really required anymore. I'll also post some instructions on how to sign packages manually for people who have the ability to make their own forks, in the repo.

**Comment by colinkiama** [comment]
New release with updated installation instructions is available here: https://github.com/colinkiama/UWP-Package-Installer/releases/tag/1.9.6.0
